### ISSUE TITLE
Retrieve specific metadata content.

### ISSUE THREAD

**Issue by dyncan** [rajnikantroy/SalesforceSimplified#1]
Hi Rajni,

First of all, thank you very much for your tools, very useful to me.

I especially like this tool to generate package.xml by clicking on it. So I have a proposal: Could we generate specific metadata files by clicking?  Because sometimes we need to get the metadata of a component, such as: profile, I have to use ant tool and config package.xml , then run the command to get metadata content, That is a little complicated.  I hope this tool can provide a way to get metadata online more efficiently.

Thanks again.

**Comment by rajnikantroy** [comment]
Hi @dyncan 

Good to know that Simplified is helping you to create package.xml.

I especially like this tool to generate package.xml by clicking on it. 
**Good to know, Thanks!**

So I have a proposal: Could we generate specific metadata files by clicking?
**Yes we can, But for this we need implementation for those metadata's.
Please give me specific metadata list which you want on Salesforce Simplified.**

Because sometimes we need to get the metadata of a component, such as: profile, I have to use ant tool and config package.xml , then run the command to get metadata content, That is a little complicated. 

I hope this tool can provide a way to get metadata online more efficiently.
**Yes! This tool is to simplify SFDC navigation and deployment work.**
